[package]
name = "rust-pssh"
version = "0.1.0"
edition = "2021"

[dependencies]
openssh = "0.10"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
